server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1KB
  http2:
    enabled: true
  servlet:
    context-path: /autopair

spring:
  datasource:
#    data: classpath:/data.sql
#    initialization-mode: always
    url: jdbc:mysql://localhost:3306/test-db?createDatabaseIfNotExist=true
    username: root
    password: 'root'
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
      hibernate.generate_statistics: true
    open-in-view: false
graphql:
  servlet:
    mapping: /graphql